name: clash_flt
description: A new Flutter plugin project.
version: 0.0.1
homepage: "https://github.com/LondonX/clash_flt"

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:

flutter:
  plugin:
    platforms:
      android:
        package: com.LondonX.clash_flt
        pluginClass: ClashFltPlugin
      ios:
        pluginClass: ClashFltPlugin
